# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import hands_pb2 as hands__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hands_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HandsServiceStub(object):
    """Hands service handles sandboxed action execution.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ExecuteAction = channel.unary_stream(
                '/kestrel.hands.HandsService/ExecuteAction',
                request_serializer=hands__pb2.ActionExecutionRequest.SerializeToString,
                response_deserializer=hands__pb2.ActionExecutionEvent.FromString,
                _registered_method=True)
        self.ListSkills = channel.unary_unary(
                '/kestrel.hands.HandsService/ListSkills',
                request_serializer=hands__pb2.ListSkillsRequest.SerializeToString,
                response_deserializer=hands__pb2.ListSkillsResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kestrel.hands.HandsService/HealthCheck',
                request_serializer=hands__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=hands__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HandsServiceServicer(object):
    """Hands service handles sandboxed action execution.
    """

    def ExecuteAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSkills(self, request, context):
        """List available skills
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HandsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ExecuteAction': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecuteAction,
                    request_deserializer=hands__pb2.ActionExecutionRequest.FromString,
                    response_serializer=hands__pb2.ActionExecutionEvent.SerializeToString,
            ),
            'ListSkills': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSkills,
                    request_deserializer=hands__pb2.ListSkillsRequest.FromString,
                    response_serializer=hands__pb2.ListSkillsResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=hands__pb2.HealthCheckRequest.FromString,
                    response_serializer=hands__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kestrel.hands.HandsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kestrel.hands.HandsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HandsService(object):
    """Hands service handles sandboxed action execution.
    """

    @staticmethod
    def ExecuteAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kestrel.hands.HandsService/ExecuteAction',
            hands__pb2.ActionExecutionRequest.SerializeToString,
            hands__pb2.ActionExecutionEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSkills(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.hands.HandsService/ListSkills',
            hands__pb2.ListSkillsRequest.SerializeToString,
            hands__pb2.ListSkillsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.hands.HandsService/HealthCheck',
            hands__pb2.HealthCheckRequest.SerializeToString,
            hands__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
