import os
import logging
from datetime import datetime, timezone

from .memory_graph import MemoryGraph

logger = logging.getLogger("brain.agent.core.markdown_memory")

class LocalMarkdownMemoryManager:
    """
    Dual Memory System: Markdown-Backed Persistence.
    Syncs the PostgreSQL/Vector DB memory graph into human-readable, editable markdown files.
    """
    
    def __init__(self, memory_graph: MemoryGraph, base_dir: str = ".kestrel_memory"):
        self.memory_graph = memory_graph
        self.base_dir = base_dir

    async def sync_workspace_to_disk(self, workspace_id: str, local_path: str = None):
        """
        Fetches the most relevant memory nodes and edges and writes them to a markdown file.
        Updates the local representation of the agent's long-term memory.
        """
        ws_uuid = self.memory_graph._to_uuid(workspace_id)
        
        async with self.memory_graph._pool.acquire() as conn:
            # Fetch top 100 most relevant entities
            nodes = await conn.fetch(
                """
                SELECT id, name, entity_type, description, weight, mention_count, last_seen
                FROM memory_graph_nodes
                WHERE workspace_id = $1
                ORDER BY weight DESC
                LIMIT 100
                """,
                ws_uuid
            )

            # Fetch relevant relationships between these top nodes
            node_ids = tuple(n["id"] for n in nodes)
            edges = []
            if node_ids:
                edges = await conn.fetch(
                    """
                    SELECT e.source_id, e.target_id, e.relation_type, e.strength, e.context
                    FROM memory_graph_edges e
                    WHERE e.source_id = ANY($1::uuid[]) AND e.target_id = ANY($1::uuid[])
                    ORDER BY e.strength DESC
                    LIMIT 200
                    """,
                    node_ids
                )

        if not nodes:
            logger.debug(f"No memory nodes to sync for workspace {workspace_id}")
            return

        # Build the Markdown Document
        lines = [
            f"# Kestrel Agent Dual-Memory",
            f"*Workspace ID: {workspace_id}*",
            f"*Last Synced: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}*",
            "",
            "> **Note**: This file is auto-generated by the LocalMarkdownMemoryManager to provide ",
            "> a transparent, human-editable text layer over the Vector DB memory graph. ",
            "> It represents the core knowledge, procedures, and rules for this workspace.",
            "",
            "## Core Knowledge Entities",
            ""
        ]

        # Map IDs to names for relationship printing
        id_to_name = {n["id"]: n["name"] for n in nodes}

        # Print Nodes
        for n in nodes:
            desc = n["description"] if n["description"] else "*No description*"
            lines.append(f"### {n['name']} ({n['entity_type']})")
            lines.append(f"- **Description:** {desc}")
            lines.append(f"- **Relevance Weight:** {float(n['weight']):.2f} (Mentions: {n['mention_count']})")
            lines.append("")

        # Print Relationships
        if edges:
            lines.append("## Semantic Relationships")
            lines.append("")
            for e in edges:
                src_name = id_to_name.get(e["source_id"], "Unknown")
                tgt_name = id_to_name.get(e["target_id"], "Unknown")
                context = f" — {e['context']}" if e["context"] else ""
                lines.append(f"- **{src_name}** -[{e['relation_type']}]-> **{tgt_name}** {context}")
            lines.append("")

        # Resolve output directory
        target_dir = local_path if local_path else os.path.join(self.base_dir, str(workspace_id))
        os.makedirs(target_dir, exist_ok=True)
        filepath = os.path.join(target_dir, ".agents.md")

        try:
            # We use standard open since sync I/O in an async context is acceptable for small local files,
            # but ideally this would use aiofiles if it were heavily concurrent.
            with open(filepath, "w", encoding="utf-8") as f:
                f.write("\n".join(lines))
            logger.info(f"Successfully synced Dual Memory markdown to {filepath}")
        except Exception as e:
            logger.error(f"Failed to sync markdown memory to {filepath}: {e}")

    async def ingest_from_disk(self, workspace_id: str, local_path: str = None):
        """
        (Hook for Bi-Directional Sync)
        Reads the local markdown file and updates the agent's context 
        if new knowledge has been manually added by the user.
        """
        # Parsing human edits from Markdown to Vector DB/Graph is complex.
        # This function acts as the integration point for future iterative bi-directional sync.
        pass
