import os
import logging
from datetime import datetime, timezone

from .memory_graph import MemoryGraph

logger = logging.getLogger("brain.agent.core.markdown_memory")

class LocalMarkdownMemoryManager:
    """
    Dual Memory System: Markdown-Backed Persistence.
    Syncs the PostgreSQL/Vector DB memory graph into human-readable, editable markdown files.
    Categorizes memory by entity type (preferences, projects, etc).
    """
    
    def __init__(self, memory_graph: MemoryGraph, base_dir: str = "~/.kestrel/memory"):
        self.memory_graph = memory_graph
        self.base_dir = os.path.expanduser(base_dir)

    async def sync_workspace_to_disk(self, workspace_id: str, local_path: str = None):
        """
        Fetches the most relevant memory nodes and edges and writes them to a markdown file.
        Updates the local representation of the agent's long-term memory.
        """
        ws_uuid = self.memory_graph._to_uuid(workspace_id)
        
        async with self.memory_graph._pool.acquire() as conn:
            # Fetch top 100 most relevant entities
            nodes = await conn.fetch(
                """
                SELECT id, name, entity_type, description, weight, mention_count, last_seen
                FROM memory_graph_nodes
                WHERE workspace_id = $1
                ORDER BY weight DESC
                LIMIT 100
                """,
                ws_uuid
            )

            # Fetch relevant relationships between these top nodes
            node_ids = tuple(n["id"] for n in nodes)
            edges = []
            if node_ids:
                edges = await conn.fetch(
                    """
                    SELECT e.source_id, e.target_id, e.relation_type, e.strength, e.context
                    FROM memory_graph_edges e
                    WHERE e.source_id = ANY($1::uuid[]) AND e.target_id = ANY($1::uuid[])
                    ORDER BY e.strength DESC
                    LIMIT 200
                    """,
                    node_ids
                )

        if not nodes:
            logger.debug(f"No memory nodes to sync for workspace {workspace_id}")
            return

        # Resolve output directory
        target_dir = local_path if local_path else os.path.join(self.base_dir, str(workspace_id))
        os.makedirs(target_dir, exist_ok=True)

        # Map IDs to names for relationship printing
        id_to_name = {n["id"]: n["name"] for n in nodes}
        
        # Group nodes by category
        grouped_nodes = {}
        for n in nodes:
            cat = n["entity_type"]
            # Pluralize simple categories for filenames
            filename = f"{cat}s.md" if cat and not cat.endswith('s') else f"{cat or 'general'}.md"
            grouped_nodes.setdefault(filename, []).append(n)

        for filename, cat_nodes in grouped_nodes.items():
            filepath = os.path.join(target_dir, filename)
            
            # Build the Markdown Document
            lines = [
                f"# Kestrel Dual-Memory: {filename.replace('.md', '').title()}",
                f"*Workspace ID: {workspace_id}*",
                f"*Last Synced: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}*",
                "",
                "> **Note**: This file is auto-generated by the LocalMarkdownMemoryManager.",
                "> You can edit the descriptions below. Kestrel will ingest changes on the next heartbeat.",
                "",
                "## Core Knowledge Entities",
                ""
            ]

            # Print Nodes
            for n in cat_nodes:
                desc = n["description"] if n["description"] else "*No description*"
                lines.append(f"### {n['name']} ({n['entity_type']})")
                lines.append(f"- **Description:** {desc}")
                lines.append(f"- **Relevance Weight:** {float(n['weight']):.2f} (Mentions: {n['mention_count']})")
                lines.append("")

            # Print Relationships relevant to these nodes
            cat_node_ids = {n["id"] for n in cat_nodes}
            cat_edges = [
                e for e in edges 
                if e["source_id"] in cat_node_ids or e["target_id"] in cat_node_ids
            ]
            
            if cat_edges:
                lines.append("## Semantic Relationships")
                lines.append("")
                for e in cat_edges:
                    src_name = id_to_name.get(e["source_id"], "Unknown")
                    tgt_name = id_to_name.get(e["target_id"], "Unknown")
                    context = f" — {e['context']}" if e["context"] else ""
                    lines.append(f"- **{src_name}** -[{e['relation_type']}]-> **{tgt_name}** {context}")
                lines.append("")

            try:
                with open(filepath, "w", encoding="utf-8") as f:
                    f.write("\n".join(lines))
                logger.info(f"Successfully synced Dual Memory markdown to {filepath}")
            except Exception as e:
                logger.error(f"Failed to sync markdown memory to {filepath}: {e}")

    async def ingest_from_disk(self, workspace_id: str, local_path: str = None):
        """
        (Hook for Bi-Directional Sync)
        Reads the local markdown files and updates the agent's context 
        if new knowledge has been manually added by the user.
        """
        import glob
        target_dir = local_path if local_path else os.path.join(self.base_dir, str(workspace_id))
        
        if not os.path.exists(target_dir):
            return

        all_matches = []
        import re
        pattern = r"### (.*?)\s*\((.*?)\)\s*\n- \*\*Description:\*\* (.*?)\n"
        
        # Also check the legacy .agents.md if it exists
        files_to_check = glob.glob(os.path.join(target_dir, "*.md"))
        legacy_file = os.path.join(target_dir, ".agents.md")
        if os.path.exists(legacy_file) and legacy_file not in files_to_check:
            files_to_check.append(legacy_file)

        for filepath in files_to_check:
            try:
                with open(filepath, "r", encoding="utf-8") as f:
                    content = f.read()
                    matches = re.findall(pattern, content)
                    all_matches.extend(matches)
            except Exception as e:
                logger.warning(f"Could not read {filepath} for memory ingestion: {e}")

        if not all_matches:
            return
            
        try:    
            ws_uuid = self.memory_graph._to_uuid(workspace_id)
            async with self.memory_graph._pool.acquire() as conn:
                for name, entity_type, desc in all_matches:
                    name = name.strip()
                    entity_type = entity_type.strip()
                    desc = desc.strip()
                    if desc == "*No description*":
                        continue
                        
                    # Upsert node based on human edits
                    await conn.execute(
                        """
                        INSERT INTO memory_graph_nodes (workspace_id, name, entity_type, description, weight, mention_count)
                        VALUES ($1, $2, $3, $4, 1.0, 1)
                        ON CONFLICT (workspace_id, name)
                        DO UPDATE SET description = EXCLUDED.description, 
                                      weight = memory_graph_nodes.weight + 0.1, 
                                      last_seen = NOW()
                        """,
                        ws_uuid, name, entity_type, desc
                    )
            logger.info(f"Successfully ingested {len(all_matches)} entities from Dual Memory markdown")
        except Exception as e:
            logger.error(f"Failed to ingest markdown memory from {target_dir}: {e}")
