from __future__ import annotations
"""
Agent-Generated UI Artifacts — persistent interactive components
created by the agent and stored as workspace-level artifacts.

Supports React/HTML components with live data bindings,
version history, and iterative refinement.
"""

import json
import logging
import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Optional

logger = logging.getLogger("brain.agent.ui_artifacts")


# ── Data Models ──────────────────────────────────────────────────────


@dataclass
class UIArtifact:
    """A persistent UI component generated by the agent."""
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    workspace_id: str = ""
    title: str = ""
    description: str = ""
    component_type: str = "react"     # react, html, markdown
    component_code: str = ""          # The actual component source
    props_schema: dict = field(default_factory=dict)
    data_source: str = ""             # Optional: API endpoint or query
    version: int = 1
    created_at: str = ""
    updated_at: str = ""
    created_by: str = ""              # agent or user_id

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "workspace_id": self.workspace_id,
            "title": self.title,
            "description": self.description,
            "component_type": self.component_type,
            "component_code": self.component_code,
            "props_schema": self.props_schema,
            "data_source": self.data_source,
            "version": self.version,
            "created_at": self.created_at,
            "updated_at": self.updated_at,
        }


@dataclass
class ArtifactVersion:
    """A historical version of a UI artifact."""
    artifact_id: str
    version: int
    component_code: str
    change_description: str = ""
    created_at: str = ""


# ── UI Artifact Manager ─────────────────────────────────────────────


class UIArtifactManager:
    """
    CRUD manager for UI artifacts with version history.

    Usage:
        mgr = UIArtifactManager(pool)
        artifact = await mgr.create(workspace_id, title, code)
        await mgr.update(artifact.id, new_code, "Fixed layout")
    """

    def __init__(self, pool=None):
        self._pool = pool
        self._artifacts: dict[str, UIArtifact] = {}
        self._versions: dict[str, list[ArtifactVersion]] = {}

    async def create(
        self,
        workspace_id: str,
        title: str,
        component_code: str,
        description: str = "",
        component_type: str = "react",
        props_schema: dict = None,
        data_source: str = "",
        created_by: str = "agent",
    ) -> UIArtifact:
        """Create a new UI artifact."""
        now = datetime.now(timezone.utc).isoformat()
        artifact = UIArtifact(
            workspace_id=workspace_id,
            title=title,
            description=description,
            component_type=component_type,
            component_code=component_code,
            props_schema=props_schema or {},
            data_source=data_source,
            version=1,
            created_at=now,
            updated_at=now,
            created_by=created_by,
        )

        self._artifacts[artifact.id] = artifact
        self._versions[artifact.id] = [
            ArtifactVersion(
                artifact_id=artifact.id,
                version=1,
                component_code=component_code,
                change_description="Initial creation",
                created_at=now,
            )
        ]

        await self._persist(artifact)
        logger.info(f"Created UI artifact '{title}' (v1)")
        return artifact

    async def update(
        self,
        artifact_id: str,
        component_code: str,
        change_description: str = "",
    ) -> Optional[UIArtifact]:
        """Update an artifact, creating a new version."""
        artifact = self._artifacts.get(artifact_id)
        if not artifact:
            return None

        artifact.version += 1
        artifact.component_code = component_code
        artifact.updated_at = datetime.now(timezone.utc).isoformat()

        # Save version
        version = ArtifactVersion(
            artifact_id=artifact_id,
            version=artifact.version,
            component_code=component_code,
            change_description=change_description,
            created_at=artifact.updated_at,
        )
        if artifact_id not in self._versions:
            self._versions[artifact_id] = []
        self._versions[artifact_id].append(version)

        await self._persist(artifact)
        logger.info(f"Updated artifact '{artifact.title}' → v{artifact.version}")
        return artifact

    async def get(self, artifact_id: str) -> Optional[UIArtifact]:
        return self._artifacts.get(artifact_id)

    async def list(self, workspace_id: str) -> list[dict]:
        return [
            a.to_dict() for a in self._artifacts.values()
            if a.workspace_id == workspace_id
        ]

    async def get_versions(self, artifact_id: str) -> list[dict]:
        versions = self._versions.get(artifact_id, [])
        return [
            {
                "version": v.version,
                "change_description": v.change_description,
                "created_at": v.created_at,
            }
            for v in versions
        ]

    async def delete(self, artifact_id: str) -> bool:
        if artifact_id in self._artifacts:
            del self._artifacts[artifact_id]
            self._versions.pop(artifact_id, None)
            return True
        return False

    async def _persist(self, artifact: UIArtifact) -> None:
        """Save artifact to the database."""
        if not self._pool:
            return
        try:
            async with self._pool.acquire() as conn:
                await conn.execute(
                    """
                    INSERT INTO ui_artifacts
                        (id, workspace_id, title, description, component_type,
                         component_code, props_schema, data_source, version,
                         created_at, updated_at, created_by)
                    VALUES ($1,$2,$3,$4,$5,$6,$7::jsonb,$8,$9,$10,$11,$12)
                    ON CONFLICT (id) DO UPDATE SET
                        component_code = EXCLUDED.component_code,
                        version = EXCLUDED.version,
                        updated_at = EXCLUDED.updated_at
                    """,
                    artifact.id, artifact.workspace_id, artifact.title,
                    artifact.description, artifact.component_type,
                    artifact.component_code, json.dumps(artifact.props_schema),
                    artifact.data_source, artifact.version,
                    artifact.created_at, artifact.updated_at,
                    artifact.created_by,
                )
        except Exception as e:
            logger.debug(f"UI artifact persistence failed: {e}")

    async def load(self, workspace_id: str) -> None:
        """Load artifacts from the database."""
        if not self._pool:
            return
        try:
            async with self._pool.acquire() as conn:
                rows = await conn.fetch(
                    "SELECT * FROM ui_artifacts WHERE workspace_id = $1",
                    workspace_id,
                )
            for row in rows:
                artifact = UIArtifact(
                    id=row["id"],
                    workspace_id=row["workspace_id"],
                    title=row["title"],
                    description=row.get("description", ""),
                    component_type=row.get("component_type", "react"),
                    component_code=row.get("component_code", ""),
                    props_schema=json.loads(row["props_schema"]) if row.get("props_schema") else {},
                    data_source=row.get("data_source", ""),
                    version=row.get("version", 1),
                    created_at=row.get("created_at", ""),
                    updated_at=row.get("updated_at", ""),
                    created_by=row.get("created_by", ""),
                )
                self._artifacts[artifact.id] = artifact
            if rows:
                logger.info(f"Loaded {len(rows)} UI artifacts for {workspace_id}")
        except Exception as e:
            logger.debug(f"No UI artifacts loaded: {e}")
