# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import brain_pb2 as brain__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in brain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub(object):
    """Brain service handles LLM inference, user management, and data CRUD
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamChat = channel.unary_stream(
                '/kestrel.brain.BrainService/StreamChat',
                request_serializer=brain__pb2.ChatRequest.SerializeToString,
                response_deserializer=brain__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/kestrel.brain.BrainService/HealthCheck',
                request_serializer=brain__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=brain__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/kestrel.brain.BrainService/CreateUser',
                request_serializer=brain__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=brain__pb2.UserResponse.FromString,
                _registered_method=True)
        self.AuthenticateUser = channel.unary_unary(
                '/kestrel.brain.BrainService/AuthenticateUser',
                request_serializer=brain__pb2.AuthenticateUserRequest.SerializeToString,
                response_deserializer=brain__pb2.AuthenticateUserResponse.FromString,
                _registered_method=True)
        self.ListWorkspaces = channel.unary_unary(
                '/kestrel.brain.BrainService/ListWorkspaces',
                request_serializer=brain__pb2.ListWorkspacesRequest.SerializeToString,
                response_deserializer=brain__pb2.ListWorkspacesResponse.FromString,
                _registered_method=True)
        self.CreateWorkspace = channel.unary_unary(
                '/kestrel.brain.BrainService/CreateWorkspace',
                request_serializer=brain__pb2.CreateWorkspaceRequest.SerializeToString,
                response_deserializer=brain__pb2.WorkspaceResponse.FromString,
                _registered_method=True)
        self.ListConversations = channel.unary_unary(
                '/kestrel.brain.BrainService/ListConversations',
                request_serializer=brain__pb2.ListConversationsRequest.SerializeToString,
                response_deserializer=brain__pb2.ListConversationsResponse.FromString,
                _registered_method=True)
        self.CreateConversation = channel.unary_unary(
                '/kestrel.brain.BrainService/CreateConversation',
                request_serializer=brain__pb2.CreateConversationRequest.SerializeToString,
                response_deserializer=brain__pb2.ConversationResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/kestrel.brain.BrainService/GetMessages',
                request_serializer=brain__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=brain__pb2.GetMessagesResponse.FromString,
                _registered_method=True)
        self.RegisterPushToken = channel.unary_unary(
                '/kestrel.brain.BrainService/RegisterPushToken',
                request_serializer=brain__pb2.RegisterPushTokenRequest.SerializeToString,
                response_deserializer=brain__pb2.RegisterPushTokenResponse.FromString,
                _registered_method=True)
        self.GetUpdates = channel.unary_unary(
                '/kestrel.brain.BrainService/GetUpdates',
                request_serializer=brain__pb2.GetUpdatesRequest.SerializeToString,
                response_deserializer=brain__pb2.GetUpdatesResponse.FromString,
                _registered_method=True)
        self.ListProviderConfigs = channel.unary_unary(
                '/kestrel.brain.BrainService/ListProviderConfigs',
                request_serializer=brain__pb2.ListProviderConfigsRequest.SerializeToString,
                response_deserializer=brain__pb2.ListProviderConfigsResponse.FromString,
                _registered_method=True)
        self.SetProviderConfig = channel.unary_unary(
                '/kestrel.brain.BrainService/SetProviderConfig',
                request_serializer=brain__pb2.SetProviderConfigRequest.SerializeToString,
                response_deserializer=brain__pb2.SetProviderConfigResponse.FromString,
                _registered_method=True)
        self.DeleteProviderConfig = channel.unary_unary(
                '/kestrel.brain.BrainService/DeleteProviderConfig',
                request_serializer=brain__pb2.DeleteProviderConfigRequest.SerializeToString,
                response_deserializer=brain__pb2.DeleteProviderConfigResponse.FromString,
                _registered_method=True)
        self.StartTask = channel.unary_stream(
                '/kestrel.brain.BrainService/StartTask',
                request_serializer=brain__pb2.StartTaskRequest.SerializeToString,
                response_deserializer=brain__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.StreamTaskEvents = channel.unary_stream(
                '/kestrel.brain.BrainService/StreamTaskEvents',
                request_serializer=brain__pb2.StreamTaskEventsRequest.SerializeToString,
                response_deserializer=brain__pb2.TaskEvent.FromString,
                _registered_method=True)
        self.ApproveAction = channel.unary_unary(
                '/kestrel.brain.BrainService/ApproveAction',
                request_serializer=brain__pb2.ApproveActionRequest.SerializeToString,
                response_deserializer=brain__pb2.ApproveActionResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/kestrel.brain.BrainService/CancelTask',
                request_serializer=brain__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=brain__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.ListTasks = channel.unary_unary(
                '/kestrel.brain.BrainService/ListTasks',
                request_serializer=brain__pb2.ListTasksRequest.SerializeToString,
                response_deserializer=brain__pb2.ListTasksResponse.FromString,
                _registered_method=True)


class BrainServiceServicer(object):
    """Brain service handles LLM inference, user management, and data CRUD
    """

    def StreamChat(self, request, context):
        """Stream chat completions with tool calling support
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health check endpoint
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """── User Management ──────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AuthenticateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWorkspaces(self, request, context):
        """── Workspace CRUD ───────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListConversations(self, request, context):
        """── Conversation CRUD ────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConversation(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterPushToken(self, request, context):
        """── Mobile / Sync ────────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUpdates(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListProviderConfigs(self, request, context):
        """── Provider Configuration ───────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProviderConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProviderConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartTask(self, request, context):
        """── Autonomous Agent ────────────────────────────────────────
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTaskEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApproveAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamChat': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamChat,
                    request_deserializer=brain__pb2.ChatRequest.FromString,
                    response_serializer=brain__pb2.ChatResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=brain__pb2.HealthCheckRequest.FromString,
                    response_serializer=brain__pb2.HealthCheckResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=brain__pb2.CreateUserRequest.FromString,
                    response_serializer=brain__pb2.UserResponse.SerializeToString,
            ),
            'AuthenticateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.AuthenticateUser,
                    request_deserializer=brain__pb2.AuthenticateUserRequest.FromString,
                    response_serializer=brain__pb2.AuthenticateUserResponse.SerializeToString,
            ),
            'ListWorkspaces': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWorkspaces,
                    request_deserializer=brain__pb2.ListWorkspacesRequest.FromString,
                    response_serializer=brain__pb2.ListWorkspacesResponse.SerializeToString,
            ),
            'CreateWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateWorkspace,
                    request_deserializer=brain__pb2.CreateWorkspaceRequest.FromString,
                    response_serializer=brain__pb2.WorkspaceResponse.SerializeToString,
            ),
            'ListConversations': grpc.unary_unary_rpc_method_handler(
                    servicer.ListConversations,
                    request_deserializer=brain__pb2.ListConversationsRequest.FromString,
                    response_serializer=brain__pb2.ListConversationsResponse.SerializeToString,
            ),
            'CreateConversation': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConversation,
                    request_deserializer=brain__pb2.CreateConversationRequest.FromString,
                    response_serializer=brain__pb2.ConversationResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=brain__pb2.GetMessagesRequest.FromString,
                    response_serializer=brain__pb2.GetMessagesResponse.SerializeToString,
            ),
            'RegisterPushToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPushToken,
                    request_deserializer=brain__pb2.RegisterPushTokenRequest.FromString,
                    response_serializer=brain__pb2.RegisterPushTokenResponse.SerializeToString,
            ),
            'GetUpdates': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUpdates,
                    request_deserializer=brain__pb2.GetUpdatesRequest.FromString,
                    response_serializer=brain__pb2.GetUpdatesResponse.SerializeToString,
            ),
            'ListProviderConfigs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListProviderConfigs,
                    request_deserializer=brain__pb2.ListProviderConfigsRequest.FromString,
                    response_serializer=brain__pb2.ListProviderConfigsResponse.SerializeToString,
            ),
            'SetProviderConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProviderConfig,
                    request_deserializer=brain__pb2.SetProviderConfigRequest.FromString,
                    response_serializer=brain__pb2.SetProviderConfigResponse.SerializeToString,
            ),
            'DeleteProviderConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProviderConfig,
                    request_deserializer=brain__pb2.DeleteProviderConfigRequest.FromString,
                    response_serializer=brain__pb2.DeleteProviderConfigResponse.SerializeToString,
            ),
            'StartTask': grpc.unary_stream_rpc_method_handler(
                    servicer.StartTask,
                    request_deserializer=brain__pb2.StartTaskRequest.FromString,
                    response_serializer=brain__pb2.TaskEvent.SerializeToString,
            ),
            'StreamTaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTaskEvents,
                    request_deserializer=brain__pb2.StreamTaskEventsRequest.FromString,
                    response_serializer=brain__pb2.TaskEvent.SerializeToString,
            ),
            'ApproveAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ApproveAction,
                    request_deserializer=brain__pb2.ApproveActionRequest.FromString,
                    response_serializer=brain__pb2.ApproveActionResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=brain__pb2.CancelTaskRequest.FromString,
                    response_serializer=brain__pb2.CancelTaskResponse.SerializeToString,
            ),
            'ListTasks': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTasks,
                    request_deserializer=brain__pb2.ListTasksRequest.FromString,
                    response_serializer=brain__pb2.ListTasksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'kestrel.brain.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('kestrel.brain.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """Brain service handles LLM inference, user management, and data CRUD
    """

    @staticmethod
    def StreamChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kestrel.brain.BrainService/StreamChat',
            brain__pb2.ChatRequest.SerializeToString,
            brain__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/HealthCheck',
            brain__pb2.HealthCheckRequest.SerializeToString,
            brain__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/CreateUser',
            brain__pb2.CreateUserRequest.SerializeToString,
            brain__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AuthenticateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/AuthenticateUser',
            brain__pb2.AuthenticateUserRequest.SerializeToString,
            brain__pb2.AuthenticateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWorkspaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/ListWorkspaces',
            brain__pb2.ListWorkspacesRequest.SerializeToString,
            brain__pb2.ListWorkspacesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/CreateWorkspace',
            brain__pb2.CreateWorkspaceRequest.SerializeToString,
            brain__pb2.WorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListConversations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/ListConversations',
            brain__pb2.ListConversationsRequest.SerializeToString,
            brain__pb2.ListConversationsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConversation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/CreateConversation',
            brain__pb2.CreateConversationRequest.SerializeToString,
            brain__pb2.ConversationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/GetMessages',
            brain__pb2.GetMessagesRequest.SerializeToString,
            brain__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterPushToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/RegisterPushToken',
            brain__pb2.RegisterPushTokenRequest.SerializeToString,
            brain__pb2.RegisterPushTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUpdates(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/GetUpdates',
            brain__pb2.GetUpdatesRequest.SerializeToString,
            brain__pb2.GetUpdatesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListProviderConfigs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/ListProviderConfigs',
            brain__pb2.ListProviderConfigsRequest.SerializeToString,
            brain__pb2.ListProviderConfigsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetProviderConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/SetProviderConfig',
            brain__pb2.SetProviderConfigRequest.SerializeToString,
            brain__pb2.SetProviderConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProviderConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/DeleteProviderConfig',
            brain__pb2.DeleteProviderConfigRequest.SerializeToString,
            brain__pb2.DeleteProviderConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kestrel.brain.BrainService/StartTask',
            brain__pb2.StartTaskRequest.SerializeToString,
            brain__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/kestrel.brain.BrainService/StreamTaskEvents',
            brain__pb2.StreamTaskEventsRequest.SerializeToString,
            brain__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApproveAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/ApproveAction',
            brain__pb2.ApproveActionRequest.SerializeToString,
            brain__pb2.ApproveActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/CancelTask',
            brain__pb2.CancelTaskRequest.SerializeToString,
            brain__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/kestrel.brain.BrainService/ListTasks',
            brain__pb2.ListTasksRequest.SerializeToString,
            brain__pb2.ListTasksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
